### ISSUE TITLE
How to create a production build?

### ISSUE THREAD

**Issue by samuelcastro** [akagr/ionic-jspm-kickstart#1]
Based on your kickstart project, how to create a production minify build?

Thank you.

**Comment by akagr** [comment]
@samuelcastro 
Haven't updated this kickstarter in a while but we're still working on a project loosely based on it. Basically, you can use jspm to minify it for you. Here's the gulp task we're using:

``` javascript
var shell = require('gulp-shell');

var bundles = [{
    name: 'bundle',
    modules: [
        'app/app'
    ]
}];

gulp.task('jspm', ['recompile-prod'], shell.task(
    bundles.map(function(bundle) {
        var modules = bundle.modules.join(' + ');
        return 'jspm bundle ' + modules + ' ' + bundle.name + '.js --no-mangle --minify --skip-source-maps';
    })
));
```

This creates a `bundle.js` which we're then sourcing in html.

**Comment by samuelcastro** [comment]
@akagr 
What's doing the 'recompile-prod' task?

Thank you.

**Comment by akagr** [comment]
In that we run a sequence of transpiling:
- scss -> css
- es6 -> es5 (via babel)
- html sanitization

the output of this task is runnable although we minify js and css via jspm in the task I shared above.

**Comment by samuelcastro** [comment]
ok, thank you a lot.
