### ISSUE TITLE
Duplicated css call

### ISSUE THREAD

**Issue by Darksoulsong** [akagr/ionic-jspm-kickstart#2]
I'm using SCSS, and I would like to disable the ionic css include from Systemjs. I tried to remove the call [from line  39](https://github.com/akagr/ionic-jspm-kickstart/blob/master/www/index.html#L39), but the css file from ionic keeps being inserted into the header. What can I do to stop this behavior? This is giving me inheritance issues.

**Comment by akagr** [comment]
Can you elaborate more on this a bit? I tried it on a vanilla build just now and removing the css import from `index.html` does work like it should. Sure you don't have the import somewhere else too?

**Comment by Darksoulsong** [comment]
@akagr 
Ok. This is my index.html file:

```
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="initial-scale=1, maximum-scale=1, user-scalable=no, width=device-width">
    <title></title>

    <link href="css/style.css" rel="stylesheet">

    <!-- IF using Sass (run gulp sass first), then uncomment below and remove the CSS includes above
    <link href="css/ionic.app.css" rel="stylesheet">
    -->

    <link href="css/ionic.app.css" rel="stylesheet">

    <!-- ionic/angularjs js -->
    <script src="lib/system.js"></script>
    <script src="js/system.config.js"></script>

    <!-- cordova script (this will be a 404 during development) -->
    <script src="cordova.js"></script>

    <!-- your app's js -->
    <link type="text/css" rel="stylesheet" href="http://localhost:8100/lib/github/driftyco/ionic-bower@1.2.4/css/ionic.css">
  </head>
  <body ng-app="starter">
    <!--
      The nav bar that will be updated as we navigate between views.
    -->
    <ion-nav-bar class="bar-stable">
      <ion-nav-back-button>
      </ion-nav-back-button>
    </ion-nav-bar>
    <!--
      The views will be rendered in the <ion-nav-view> directive below
      Templates are in the /templates folder (but you could also
      have templates inline in this html file if you'd like).
    -->
    <ion-nav-view></ion-nav-view>
    <script type="text/javascript">
        System.import("js/app");
        // System.import('ionic/css/ionic.min.css!')
    </script>
  </body>
</html>
```

Right before `</head>`, Systemjs is dynamically inserting a style tag, containing  the path to  ionic stylesheet, and this is happening even after I comment line 39.

**Comment by akagr** [comment]
I haven't come across a situation where system.js has injected an asset right in the html. Not sure that it can even do that. Also, (un)commenting the system import doesn't do this since it doesn't work that way. I suggest you take a look at your gulp/grunt configuration. Those are the most likely places where code is generally injected in html.

**Comment by Darksoulsong** [comment]
@akagr I spent a couple of hours debugging this and find out the problem: the `ionic-angular` lib has some kind of "import" declaration at the beginning of the file, like so: `"deps ../css/ionic.css!";` I just commented the line and everything is fine now. Too bad I had to edit a source file to solve this.

Thank you very much for the help!

**Comment by akagr** [comment]
That's interesting. I wonder why it worked for me then. Will try to scope it out later. Glad to know you've got it working though.
